### ISSUE TITLE
Extension fails on install

### ISSUE THREAD

**Issue by pojke** [Chassis/chassis_openssl#9]
1. What operating system do you use?
**Win10**
2. What version of Vagrant are you running?
**2.2.4**

3. Are you using VirtualBox or VMWare and which version are you using?
**VB Version 6.0.14 r133895 (Qt5.6.2)**

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
**Out of the box Chassis**

5. Do you have any Chassis other extensions installed? If so, what are they?
**PHPMyAdmin**

Out of the box install fails with the following error:
```==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class chassis-openssl at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node vagrant.local
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class chassis-openssl at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node vagrant.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

**Comment by BronsonQuick** [comment]
Can you please try changing the folder name from `chassis-openssl` to `chassis_openssl` and run `vagrant provision` that should fix it and we'll need to update the readme.

**Comment by pojke** [comment]
Yup it's working, thanks Bronson :-)
